### ISSUE TITLE
Search elements by Id on CollectionWrapper

### ISSUE THREAD

**Issue by ste8** [ProximoSrl/Jarvis.Framework#5]
When I search an element by Id on CollectionWrapper using an instruction such as "collection.Contains(x => x.Id == id)" and CollectionWrapper is working in-memory, the search operation is not executed by index, it needs a full scan of the values of the dictionary contained in the in-memory collection.

Is it possible to add a way to search by Id without a full scan?

**Comment by alkampfergit** [comment]
CollectionWrapper has FindOneById and also now has FindAndModifyByProperty and FindByProperty that allows to search element with a property equal to a given value using an in-memory index when nitro is enabled.
